# Generated by Django 4.1.2 on 2022-11-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor',
            new_name='Doctors',
        ),
    ]
